### ISSUE TITLE
[FR] Improve overall error handling and fault tolerance

### ISSUE THREAD

**Issue by sserrata** [PaloAltoNetworks/docusaurus-openapi-docs#111]
### Is your feature request related to a problem?

Under most circumstances, the `docusaurus-plugin-openapi-docs` plugin successfully reads, parses and generates MDX for a given OpenAPI specification. Still, there are times when processing errors occur, due to gaps or incompatibilities, which can lead to exceptions. These errors can occur for a number of reasons at a number of points during processing, including:

* Conversion of OAS to postman collection
* Creation of API items (especially when creating sample request payloads/schemas)

### Describe the solution you'd like

* Better, more informative errors/traces, i.e. include function, spec path, etc.
* Better fault tolerance, i.e. continue processing other specs after failure
* Pre-flight validation checks before proceeding with deeper processing

### Describe alternatives you've considered

Focusing more on validating the OAS outside of the plugin using various linters, extensions, tools, etc.

### Additional context

Improvements in this area would greatly enhance the usability of the plugin while also decreasing the time needed to diagnose failures and deliver fixes.

### TODO

- [ ] Document process flow (diagram?) and where failures could occur
- [ ] Implement pre-flight validation to help fail faster
- [ ] Add appropriate exception handling to functions prone to failure
- [ ] Pass/add appropriate context to improve error messages
- [ ] Support continue on failure/error
- [ ] Improve logging, i.e. provide more logging to understand where we are in the process

### Smaller Fixes

- [x] PAN-OS REST API `[ERROR] TypeError: Cannot read properties of undefined (reading 'default')`

**Comment by sserrata** [comment]
After some internal discussion, we determined it would be better to focus on improving our testbed. Archiving this issue for now.
